### ISSUE TITLE
OperatorAutoConfiguration forms a bean dependency cycle with simplest setup

### ISSUE THREAD

**Issue by erikgb** [ContainerSolutions/java-operator-sdk#102]
The kubernetesClient bean defined in `OperatorAutoConfiguration` is not very usable at the moment.
 
Most `ResourceController` beans will have a dependency to a KubernetesClient bean. This means that  to get any value from the kubernetesClient bean defined in `OperatorAutoConfiguration`, the kubernetesClient bean will have to be created **before** your controller bean. And that is not possible now, since the `OperatorAutoConfiguration` class is defined to autowire the list of `ResourceController` beans.

Sample log output when trying to start the simplest application:
```log
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  splunkIndexController defined in file [/home/erikbo/projects/stas/splunk-index-operator/target/classes/no/statnett/stas/operator/splunk/SplunkIndexController.class]
↑     ↓
|  com.github.containersolutions.operator.spingboot.starter.OperatorAutoConfiguration (field private java.util.List com.github.containersolutions.operator.spingboot.starter.OperatorAutoConfiguration.resourceControllers)
└─────┘
```

My suggestion is to either:

1. Remove the `OperatorAutoConfiguration#resourceControllers` field, and replace it with an autowired parameter to the `OperatorAutoConfiguration#operator` method.

1. Move the kubernetesClient bean to another (auto) `Configuration` class.

**Comment by csviri** [comment]
Hi @erikgb , thx for feedback, I created a PR that improves the auto config a bit
https://github.com/ContainerSolutions/java-operator-sdk/pull/103

although I'm not sure this fixes you issue, however in the sample usage we have exactly this case covered (if I you understand your description correctly):
https://github.com/ContainerSolutions/java-operator-sdk/tree/master/samples/spring-boot-auto-config

I'm not sure why the `OperatorAutoConfiguration.resourceController` is autowired into your controller, If you can share you full code somehow I can take a look.

**Comment by erikgb** [comment]
@csviri The problem is that `SplunkIndexController` _is a_ `ResourceController` bean, that requires a `KubernetesClient` bean. This creates the following dependency cycle (because of the autowired field `OperatorAutoConfiguration#resourceControllers` ) :

`SplunkIndexController`->`OperatorAutoConfiguration`->`SplunkIndexController`

I managed to workaround this issue by creating my own `KubernetesClient` bean - thus breaking the cycle. I think your PR https://github.com/ContainerSolutions/java-operator-sdk/pull/103 will fix the issue. Thanks!

Some simple smoke tests of the samples would be an improvement.

**Comment by csviri** [comment]
@erikgb I added smoke tests into the sample (pls check the PR again). Again, in the sample, we are doing the same thing, but this should not be an issue, if you define everything as a bean (as you can see in the sample). 

Since there is no real cyclic dependency between the beans. Unless you do some exotic thing like really autowireing the `OperatorAutoConfiguration` or things like that. 

Spring just gets all the beans defined in configuration classes, makes a graph and if there is no cycle in it then its fine. In this case is not: `KubernetesClient` -> `ResourceController` -> `Operator`

But if you share you whole code in a project on Github I can take a look.
