### ISSUE TITLE
Instance of a custom operator is created in default namespace

### ISSUE THREAD

**Issue by sjmittal** [ContainerSolutions/java-operator-sdk#112]
Hi,
I am facing this issue which for some reason I am not able to wrap my head around it.
I have defined a CRD of my custom operator.
I have set:
`scope: Namespaced`
Then I deploy my operator in a given namespace.
```
metadata:
  name: objectstore-operator
  namespace: objectstore-operator
```

However when the operator framework creates an instance of my custom operator then this gets created in default namespace.

Any idea why this is happening. I see a MR on this:
https://github.com/ContainerSolutions/java-operator-sdk/pull/62

Doesn't this suppose to fix this issue. Is there anything I should be checking that I may be doing wrong.

My operator's instance 's yaml is something like:
```
apiVersion: sample.javaoperatorsdk/v1
kind: ObjectStore
metadata:
  name: my-objectstore
spec:
  ...

```
Is there something I need to add in here to force it to be deployed in same namesapace as the operator's.

Thanks
Sachin

**Comment by adam-sandor** [comment]
This is probably caused by not specifying the namespace in the fabric8 client call when creating the CR. Can you share the part of the code where you are saving the new custom resource?

**Comment by sjmittal** [comment]
How I understand is the java operator framework essentially creates the instance of new custom resource and we can then control this custom resource to create and manage other deployments.

Here is the code which is entry point of my custom operator: 
https://github.com/sjmittal/java-operator-sdk/blob/sample-minio-operator/samples/minio-objectstore/src/main/java/com/github/containersolutions/operator/sample/ObjectStoreOperator.java

And here the code for my operator's controller:
https://github.com/sjmittal/java-operator-sdk/blob/sample-minio-operator/samples/minio-objectstore/src/main/java/com/github/containersolutions/operator/sample/ObjectStoreController.java
Note that in here when I print the namespace I get this as default.
```
String osNS = objectStore.getMetadata().getNamespace();
log.info("Objectstore namespace {}", osNS);

```

**Comment by adam-sandor** [comment]
As I understand it you are reading ObjectStore Custom Resources and creating MinioInstance CRs. You are reading the namespace from the ObjectStore resource, so the namespace will be the namespace where you created the ObjectStore (probably using kubectl). This means the namespace is not controlled by the operator but by you when creating that resource. Does this make sense?

**Comment by sjmittal** [comment]
yes this makes sense. I now realize that CRD's instance's are created using kubectl and not using operator's controller. The controller actually manages what the instance itself needs to create or control.

**Comment by adam-sandor** [comment]
Exactly, it's a bit tricky to wrap your head around all of it. Glad you're making good progress, keep it up 💪🏻
