### ISSUE TITLE
How to handle errors/exceptions in ResourceController

### ISSUE THREAD

**Issue by sjmittal** [ContainerSolutions/java-operator-sdk#116]
Hello folks,
I wanted to know how to handle errors/exceptions in the createOrUpdateResource or deleteResource callbacks.

Say when creating or updating a resource it throws and un handled exception, then does the operator framework retries the same?

Also say we handled the exception and set the status as say "error", then we would want the framework to again try same method until we have our "success" status.

How can we achieve the same.

Thanks
Sachin

**Comment by csviri** [comment]
Hi @sjmittal,

in general you can path a Retry when registering a controller. If the controller throws any exception the execution is considered to be failed, and going to be automatically retried based on Retry configuration.
pls see retry package for details:
https://github.com/ContainerSolutions/java-operator-sdk/tree/master/operator-framework/src/main/java/com/github/containersolutions/operator/processing/retry

GenericRetry covers most of the cases, we could think of.

Handling status is up to the user, note that there is no unified way in custom resources to handle status structure, so you have to handle in you custom specific way. The easiest way is just, return your CustomResource from the controller createOrUpdate method, where you set some status. This will trigger an automatic update for the CR.

**Comment by sjmittal** [comment]
I checked the retry mechanism and throwing runtime exception is one way. I will try that out. However in retry there is some limit on number of retries. I suppose I need to extend that base classes if I need to retry till I get the desired state?

However I did not understand clearly that how can I ensure that if specific status is set, which triggers automatic update of the CR, will also ensure the retry.
Let me present my understanding and please let me know if I am getting this right:

1. Say for CR I set `status = X` (for the first time)
2. This updates the CR which again calls `createOrUpdate` and if I again set `status = X` then it does not call again (unless the CR is modified).
3. So if `X <=> error` it will trigger next round and then if I set `status = Y`, it again triggers next round.
4. Now since `Y <=> success`, which is again set as status, it does not trigger further rounds of `createOrUpdate` (unless the CR is modified).
4. However if for second round I again set status as `X` (which is error) then it will still not trigger the next round because CR does not get updated. I suppose to circumvent this I may need to set status as `X <counter>` till I get the success status (`Y`). Or figure out to achieve this by throwing runtime exceptions.

Please let me know if I am on right track and these are couple of ways to enure retries.

**Comment by csviri** [comment]
@sjmittal 
there is a method on GenericRetry:
`
public GenericRetry withoutMaxAttempts() {
        return this.setMaxAttempts(-1);
}
`
this will unset the upper bound. However this is probably you don't want, since there is some programmatic bug, or config error, this should fail. This issue will also ensure you will be able to get after the limit a notification: https://github.com/ContainerSolutions/java-operator-sdk/issues/39

Regarding the triggering and the statuses. The framework is not aware what fields are you setting. So if you change anything  - currently other than `.metadata`-  it will trigger a new event, since its a change to custom resource. 

Since this is an update on status not on spec the new event will trigger again the the execution, however since the spec is not changed and operation should be idempotent this should not cause an issue (for now just ignore this round). 

You are right that currently you are not able to check how many times its executed, and maybe we should have a support to check this. Will take a look on this asap.

Note to not get update from status updates, the correct way to do this is to use sub-resources:
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#subresources

See also this in fabric8 client: 
https://github.com/fabric8io/kubernetes-client/issues/1548

currently this is an issues I'm working on to support sub resource, will take a look also so support the information about retries in the controller, so you will be able to set error status based on that.

**Comment by adam-sandor** [comment]
@sjmittal Can you get in touch with me at adam.sandor at container-solutions dot com? I would love to know more about what you're working on an invite you for our meetings about the operator sdk. You are our most active user and we are very grateful for all your input!

**Comment by sjmittal** [comment]
@csviri 
I am following the instructions given by you below
> Since this is an update on status not on spec the new event will trigger again the the execution, however the spec is not changed and operation should be idempotent, therefore this should not cause an issue

These are the logs I get:
`[36mc.g.c.o.p.EventScheduler      [m [36m[DEBUG] Event received for action: added, ...`

So controller processes the custom resource and updates the status of the custom resource.
Then I see this:
```
[36mc.g.c.o.p.EventDispatcher     [m [36m[DEBUG] Trying to replace resource ... version: 70866
[36mc.g.c.o.p.EventScheduler      [m [36m[DEBUG] Event received for action: modified, ...
[36mc.g.c.o.p.EventScheduler      [m [36m[DEBUG] Scheduling event from Api: CustomResourceEvent{action=MODIFIED, resource=[ ... ,resourceVersion=70885, markedForDeletion: false ], retriesIndex=-1}
```
So as explained by you it will again schedule the event and I also see that resource version is updated. So far so good.

However I also see this in the next logs:
```
[m [36mc.g.c.o.p.EventScheduler      [m [36m[DEBUG] Skipping event, has not larger generation than last stored, actual generation: 1, last stored: 1
```
Now I check the link
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#status-subresource
It states that:
`The .metadata.generation value is incremented for all changes, except for changes to .metadata or .status.`

So I am bit confused that is that in order to re-trigger the event processing do I need to update the status field of my CR or of my CR's sub-resource?

**Comment by csviri** [comment]
@sjmittal, in short the status field.

In order to use status sub-resource you have to define the status as a sub-resource in CRD, and there a special method to update that in the fabric8 client. We will have better support for this soon.  If you don't define status as a subresource, but just a field, it should trigger an event and a generation increase.

**Comment by sjmittal** [comment]
@csviri currently in fabric8 client there are methods to update status under: `CustomResourceOperationsImpl`
However it is not clear to me how to trigger the call to update the status subresource.
In the controller, we only have the reference to the `CustomResource` instance. The client to handle custom resource is created by the framwork and the controller does not have access to that client.

I suppose you would need to modify the call `controller.createOrUpdateResource(resource)` to also include the custom resource client as one to the arguments, or you need to handle this in the `EventDispatcher#handleEvent` method.

I doubt right now there is an effective way to trigger sub-resource status update. For now I am trying to set `generationAwareEventProcessing = false` to see if this workaround works.

**Comment by csviri** [comment]
@sjmittal the setting of client will be a separate interface to implement, 
see: https://github.com/ContainerSolutions/java-operator-sdk/blob/client-awareness/operator-framework/src/main/java/com/github/containersolutions/operator/api/CustomResourceClientAware.java

for now you can create a resource client manually and set it to the controller.

**Comment by sjmittal** [comment]
@csviri 
I noticed something that if I define a status sub-resource for my `CRD` then my `CR`'s status does not get updated. 
Also as per docs: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#status-subresource, one need to invoke `PUT` to `/status` path to get the status updated.
Could you please check the PR https://github.com/ContainerSolutions/java-operator-sdk/pull/118
After this change I now see that status are getting updated and shown when i describe my `CR`. 

Please check if this code make sense or if there is some other way to trigger status update.

**Comment by csviri** [comment]
@sjmittal  this I can't accept, we would look generality, thus the implementation won't be able to update other part of custom resource. You have to do it from controller implementation with a client for resource you create, or wait until I finish the injecting of resource client, that will contain a sample how to do it.

**Comment by sjmittal** [comment]
@csviri 
Well for now I will wait till we have a way to inject resource client in controller. This workaround is anyway temporary for local case.
There is another thing I found around this is in this piece of code:
https://github.com/ContainerSolutions/java-operator-sdk/blob/master/operator-framework/src/main/java/com/github/containersolutions/operator/processing/EventDispatcher.java#L114

What I observe is that say in my controller I modified a field from the `spec` stanza and when this line is invoked, it somehow does not update the `generation` and hence modified event is not scheduled to be processed again.

Any idea why we are using `lockResourceVersion` here. And if we want to update `spec` of our custom resource based on which we would like the controller to retry again, how can this be achieved. I think right now controller is triggered only if we update spec directly into `k8s`, outside of the framework.

**Comment by csviri** [comment]
@sjmittal did you check the latest release? if it solves also you problems?

**Comment by sjmittal** [comment]
@csviri  Right now I am working on pushing the current deployment with current version of operator's framework.
Once we are able to automate this part, for next set of operators and also current ones we would upgrade to framework's latest release. I will update you, but this may take a while.

Thanks
Scahin

**Comment by csviri** [comment]
@sjmittal kk, good luck, let us know if you need help!

**Comment by csviri** [comment]
will close this issue now, we can reopen if we see that there are new requirements with the updated api
