### ISSUE TITLE
Fix: Doneable class needs to be always created for custom resource

### ISSUE THREAD

**Issue by csviri** [ContainerSolutions/java-operator-sdk#27]
This seems to be just an issue how fabric8 is hadling reflection internally, try to patch this in fabric8 client, so no boilerplate code is needed in addition to cutom resource class.

(List is actually not needed)

**Comment by kirek007** [comment]
Hi, I'll take care of that one :)

**Comment by cs-marek-ruszczyk** [comment]
Hi, I'll take care of this one! :)

**Comment by charlottemach** [comment]
The main contributor to the fabric8 client says it's not possible to have a default for the doneable class, as it's a builder (https://groups.google.com/forum/#!topic/fabric8/Q5_aSYyaAtA), so I'm looking into just creating some on our side.

**Comment by csviri** [comment]
@charlottemach  nice work, will close this!
