### ISSUE TITLE
Quarkus integration

### ISSUE THREAD

**Issue by adam-sandor** [ContainerSolutions/java-operator-sdk#65]
[Quarkus](quarkus.io) provides Java with go-like startup time and memory footprint. As we are targeting Kubernetes-land where people love go, and hate Java for startup time and memory footprint (even if they are irrelevant for operators) we could try how would Quarkus improve things. It's also the main "Cloud Native Java" framework right now, so we could ride that wave.

**Comment by csviri** [comment]
Hmm, mabe we should focus just directly on GraalVM, not sure.

**Comment by adam-sandor** [comment]
Closed to create 2 more narrow issues
