### ISSUE TITLE
Integration tests unreliable (intermittent failures)

### ISSUE THREAD

**Issue by adam-sandor** [ContainerSolutions/java-operator-sdk#68]
The integration tests are failing when the namespace doesn't yet exist. Might not be the only case but that's when I saw it.
Tested with: Docker for Mac & GKE

**Comment by adam-sandor** [comment]
[manyResourcesTest-error.txt](https://github.com/ContainerSolutions/java-operator-sdk/files/4471324/manyResourcesTest-error.txt)

**Comment by csviri** [comment]
@adam-sandor I run the tests against EKS, GKE, minikube. But was not able to reproduce this.
Also not clear me from logs what is the issue. Maybe we should take a look together.
