### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by JRial95** [ContainerSolutions/java-operator-sdk#69]
The pull request #66 introduces a quite old version of Javassist (version 3.8.0.GA released in 2009). This version throws warnings on recent versions of Java (tested on Java 13):
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.ClassPool (file:/root/.gradle/caches/modules-2/files-2.1/jboss/javassist/3.8.0.GA/d41b5be5d26d4def2e26f996337d512d86509de8/javassist-3.8.0.GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of javassist.ClassPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
The solution is to update this library from `jboss:javassist:3.8.0.GA` to `org.javassist:javassist:3.27.0-GA` and modify the `toClass()` call in `ControllerUtils.java`.

**Comment by csviri** [comment]
cool! thx!

**Comment by JRial95** [comment]
It looks like my pull request doesn't pass the integration tests. After investigation, it occurs only with Java 8 because the `toClass(Class<?> neighbor)` method is available for Java 9 and newer. Fixing the problem by using the `toClass()` method (commit e6868b5) works but the warnings reappear. 

In order to fix the warnings issue and keep this code running in Java 8, I propose to change the `toClass()` method according to the Java version with a simple `if` like 0d85199. @csviri What do you think about this solution?

This time, I tested with different versions of Java (from 8 to 15 using the `openjdk:<version>` docker images). The integration tests pass on all versions except Java 10 where the original code also doesn't work due to a strange `SurefireBooterForkException` (should I open an issue for that ?).

**Comment by csviri** [comment]
Yep, looks good, please create a separate PR!, thx!
