### ISSUE TITLE
Question on deploying and packagin

### ISSUE THREAD

**Issue by yonimoses** [ContainerSolutions/java-operator-sdk#71]
Hi
First, a very cool project ;)

I'm trying to deploy the boot sample without any luck on listening for incoming resources.
I've deployed my boot (based on 0.3.10-SNAPSHOT) 
log says "2020-04-15 16:52:41.402  INFO 1 --- [           main] c.g.c.operator.Operator                  : Registered Controller: 'CustomServiceController' for CRD: 'class example.smallest.CustomService' for namespaces: [all/client namespace]" 

but when i deploy a cr i get nothing ;(

my config is as follows 

`
@Controller(customResourceClass = CustomService.class,
        crdName = "customservices.sample.javaoperatorsdk")
`
`
public class CustomService extends CustomResource {

    private ServiceSpec spec;

    ....
}
`

the CRD is taked from the master branch.

Any ideas?

**Comment by JRial95** [comment]
I had the same issue. To make this sample working for all namespaces, replace this line
https://github.com/ContainerSolutions/java-operator-sdk/blob/e6868b567442a854d89861d878488fe427535e08/samples/basic/spring-boot/src/main/java/com/github/containersolutions/operator/sample/Config.java#L29
with 

```controllers.forEach(operator::registerControllerForAllNamespaces);```

**Comment by csviri** [comment]
Yep, that should be the way to do it!

**Comment by yonimoses** [comment]
Working! :)
Thanks for that.
