### ISSUE TITLE
Add GitHub actions release workflow

### ISSUE THREAD

**Issue by csviri** [ContainerSolutions/java-operator-sdk#78]
Should be triggered by release creation:
https://help.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-maven

**Comment by adam-sandor** [comment]
![image](https://user-images.githubusercontent.com/10675791/80318062-cb966080-8807-11ea-8a8b-d9b682950563.png)

**Comment by csviri** [comment]
https://github.com/samuelmeuli/action-maven-publish

**Comment by csviri** [comment]
fixed
