### ISSUE TITLE
Create Nicer User Guide 

### ISSUE THREAD

**Issue by csviri** [ContainerSolutions/java-operator-sdk#84]
- its probably enough just to add it to the Readme.md for now

**Comment by frankkoornstra** [comment]
It'd be really nice to have a short section on how to make things work with Spring :pray:

**Comment by csviri** [comment]
@frankkoornstra  Yep, will add a nice user manual soon. For you can take a look on the spring boot auto config example:
https://github.com/ContainerSolutions/java-operator-sdk/tree/master/samples/basic/spring-boot

**Comment by csviri** [comment]
Created a skeleton of this, will continuously update it. I close this issue for now.
