### ISSUE TITLE
MySQLSchema example should create Secret with database connection params

### ISSUE THREAD

**Issue by adam-sandor** [ContainerSolutions/java-operator-sdk#95]
The MySQLSchemaOperator doesn't provide a way for an application to connect to the database it created. The solution would be:
1. Create a user with a  random password when creating the schema
2. Put the user credentials and the URL to the database into a Secret

Not only can an application now mount the Secret to connect to the database, but also the username/password are dynamically generated for improved security.

**Comment by csviri** [comment]
@adam-sandor should not we separate this operator to a new repository?

**Comment by adam-sandor** [comment]
I don't know.. how would that help?

**Comment by csviri** [comment]
We already have a  the WebServer example, which is the complex one. Don't see shy should we have two. We could have this schema operator as something that is not just an example,  but could be a sample standalone "project" using the SDK.
